# Generated by Django 5.2.5 on 2025-09-01 20:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0003_copy_theme_to_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('city', 'City'), ('neighborhood', 'Neighborhood')], default='city', max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('geojson', models.TextField(blank=True, null=True)),
                ('center_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('center_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('population_note', models.TextField(blank=True)),
                ('permits_links', wagtail.fields.StreamField([('link', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.URLBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('url', 1)]], {})})),
                ('parent_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighborhoods', to='website.geoarea')),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='projectpage',
            name='geoareas',
            field=models.ManyToManyField(blank=True, related_name='projects', to='website.geoarea'),
        ),
        migrations.CreateModel(
            name='ServiceCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready')], default='draft', max_length=10)),
                ('unique_intro', wagtail.fields.RichTextField(blank=True)),
                ('pain_points_local', wagtail.fields.StreamField([('point', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})})),
                ('process_steps_local', wagtail.fields.StreamField([('step', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})})),
                ('permits_local', wagtail.fields.StreamField([('permit', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1)]], {})})),
                ('starting_price_local', models.CharField(blank=True, max_length=80)),
                ('cta_local', models.CharField(blank=True, max_length=120)),
                ('schema_overrides', models.JSONField(blank=True, default=dict)),
                ('geoarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='website.geoarea')),
                ('hero_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='website.servicepage')),
            ],
            options={
                'unique_together': {('service', 'geoarea')},
            },
        ),
    ]
