# Generated by Django 5.2.5 on 2025-09-01 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('website', '0005_testimonial_geoarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_seo_enabled', models.BooleanField(default=False)),
                ('primary_city_slug', models.SlugField(blank=True, max_length=140)),
                ('gbp_url', models.URLField(blank=True)),
                ('service_radius_km', models.IntegerField(default=0)),
                ('default_utm_source', models.CharField(blank=True, max_length=80)),
                ('default_utm_campaign', models.CharField(blank=True, max_length=80)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
