# Generated by Django 5.2.5 on 2025-09-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0006_localseosettings'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicecoverage',
            index=models.Index(fields=['service', 'geoarea'], name='website_ser_service_ac0760_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['geoarea'], name='website_tes_geoarea_9c557f_idx'),
        ),
    ]
