# Generated by Django 5.2.5 on 2025-09-02 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_add_indexes_servicecoverage_testimonial'),
        ('website', '0007_servicecoverage_website_ser_service_ac0760_idx_and_more'),
    ]

    operations = [
    ]
