# Generated by Django 5.2.5 on 2025-09-02 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_merge_20250901_2124'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='servicecoverage',
            name='svc_geo_idx',
        ),
        migrations.RemoveIndex(
            model_name='testimonial',
            name='testimonial_geo_idx',
        ),
    ]
