# Generated by Django 5.2.5 on 2025-09-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_servicecoverage_svc_geo_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoarea',
            name='neighbors',
            field=models.ManyToManyField(blank=True, related_name='neighbor_of', to='website.geoarea'),
        ),
        migrations.AddIndex(
            model_name='geoarea',
            index=models.Index(fields=['slug'], name='website_geo_slug_c477c6_idx'),
        ),
    ]
