# Generated by Django 5.2.5 on 2025-09-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_geoarea_neighbors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='cta_hint',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
