# Generated by Django 5.2.5 on 2025-09-04 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_servicepage_cta_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='geo',
            field=models.ForeignKey(blank=True, help_text='Link to the real SEO geo area for service coverage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_areas', to='website.geoarea'),
        ),
    ]
