services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: trades
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trades
    ports: ['5432:5432']
    volumes: [db:/var/lib/postgresql/data]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ['9000:9000', '9001:9001']
    volumes: [minio:/data]

volumes:
  db:
  minio:
