# Generated by Django 5.2.5 on 2025-08-31 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0002_alter_theme_options_theme_created_at_and_more'),
        ('sitecontent', '0002_delete_theme_snippet'),
    ]

    operations = [
    ]
